# Generated by Django 6.1 on 2026-09-04 11:47

import core.images
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('name_fa', models.CharField(max_length=100, null=True, verbose_name='نام دسته\u200cبندی')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='نامک (URL)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی خبر',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای اخبار',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=200, null=True, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='نامک (URL)')),
                ('summary', models.CharField(max_length=300, verbose_name='خلاصه')),
                ('summary_fa', models.CharField(max_length=300, null=True, verbose_name='خلاصه')),
                ('summary_en', models.CharField(max_length=300, null=True, verbose_name='خلاصه')),
                ('body', models.TextField(verbose_name='متن کامل')),
                ('body_fa', models.TextField(null=True, verbose_name='متن کامل')),
                ('body_en', models.TextField(null=True, verbose_name='متن کامل')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='تصویر شاخص')),
                ('meta_description', models.CharField(blank=True, help_text='اگر خالی بماند، از خلاصه استفاده می\u200cشود.', max_length=300, verbose_name='توضیح متا')),
                ('meta_description_fa', models.CharField(blank=True, help_text='اگر خالی بماند، از خلاصه استفاده می\u200cشود.', max_length=300, null=True, verbose_name='توضیح متا')),
                ('meta_description_en', models.CharField(blank=True, help_text='اگر خالی بماند، از خلاصه استفاده می\u200cشود.', max_length=300, null=True, verbose_name='توضیح متا')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='news.postcategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'خبر / مقاله',
                'verbose_name_plural': 'اخبار و مقالات',
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['is_published', '-published_at'], name='post_pub_date_idx')],
            },
            bases=(core.images.OptimizedImagesMixin, models.Model),
        ),
    ]
