# Generated by Django 6.1 on 2026-08-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام شرکت')),
                ('logo', models.ImageField(upload_to='company/', verbose_name='لوگو')),
                ('tagline', models.CharField(blank=True, max_length=250, verbose_name='شعار شرکت')),
                ('hero_text', models.TextField(verbose_name='متن معرفی صفحه اصلی')),
                ('about_text', models.TextField(verbose_name='متن درباره ما')),
                ('address', models.CharField(max_length=300, verbose_name='آدرس')),
                ('phone', models.CharField(max_length=20, verbose_name='تلفن')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('working_hours', models.CharField(blank=True, max_length=150, verbose_name='ساعات کاری')),
                ('instagram_url', models.URLField(blank=True, verbose_name='لینک اینستاگرام')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='لینک لینکدین')),
                ('telegram_url', models.URLField(blank=True, verbose_name='لینک تلگرام')),
            ],
            options={
                'verbose_name': 'اطلاعات شرکت',
                'verbose_name_plural': 'اطلاعات شرکت',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان خدمت')),
                ('description', models.TextField(verbose_name='توضیح خدمت')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='آیکون/تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['order'],
            },
        ),
    ]
