# Generated by Django 6.1 on 2026-08-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='about_text_en',
            field=models.TextField(null=True, verbose_name='متن درباره ما'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_text_fa',
            field=models.TextField(null=True, verbose_name='متن درباره ما'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='address_en',
            field=models.CharField(max_length=300, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='address_fa',
            field=models.CharField(max_length=300, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_text_en',
            field=models.TextField(null=True, verbose_name='متن معرفی صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_text_fa',
            field=models.TextField(null=True, verbose_name='متن معرفی صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='نام شرکت'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='name_fa',
            field=models.CharField(max_length=150, null=True, verbose_name='نام شرکت'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tagline_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='شعار شرکت'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tagline_fa',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='شعار شرکت'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='working_hours_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ساعات کاری'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='working_hours_fa',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ساعات کاری'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True, verbose_name='توضیح خدمت'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_fa',
            field=models.TextField(null=True, verbose_name='توضیح خدمت'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='عنوان خدمت'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_fa',
            field=models.CharField(max_length=150, null=True, verbose_name='عنوان خدمت'),
        ),
    ]
