# Generated by Django 6.1 on 2026-09-04 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companyinfo_about_text_en_companyinfo_about_text_fa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=150, null=True, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('icon', models.CharField(choices=[('icon-molecule', 'مولکول / اکسیژن'), ('icon-gauge', 'فشارسنج / دقت'), ('icon-shield', 'سپر / ایمنی'), ('icon-support', 'پشتیبانی فنی'), ('icon-cog', 'چرخ\u200cدنده / مهندسی'), ('icon-factory', 'کارخانه / تولید'), ('icon-chip', 'مدار / کنترل هوشمند'), ('icon-flask', 'آزمایشگاه / تحقیق'), ('icon-certificate', 'گواهی / استاندارد'), ('icon-layers', 'لایه\u200cها / ماژولار'), ('icon-target', 'هدف / دقت عملکرد'), ('icon-chart', 'نمودار / بهره\u200cوری'), ('icon-globe', 'جهانی / صادرات'), ('icon-hospital', 'درمان / بیمارستان'), ('icon-wrench', 'سرویس و نگهداری'), ('icon-clock', 'زمان / ساعات کاری'), ('icon-users', 'تیم / نیروی انسانی'), ('icon-box', 'محصول / بسته\u200cبندی'), ('icon-check', 'تأیید / کیفیت'), ('icon-spark', 'نوآوری'), ('icon-pin', 'موقعیت مکانی'), ('icon-phone', 'تلفن'), ('icon-mail', 'ایمیل')], default='icon-cog', help_text='آیکون برداری از فهرست آماده؛ نیازی به آپلود تصویر نیست.', max_length=40, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
            ],
            options={
                'verbose_name': 'مزیت رقابتی',
                'verbose_name_plural': 'مزایای رقابتی (چرا ما)',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=150, null=True, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('icon', models.CharField(choices=[('icon-molecule', 'مولکول / اکسیژن'), ('icon-gauge', 'فشارسنج / دقت'), ('icon-shield', 'سپر / ایمنی'), ('icon-support', 'پشتیبانی فنی'), ('icon-cog', 'چرخ\u200cدنده / مهندسی'), ('icon-factory', 'کارخانه / تولید'), ('icon-chip', 'مدار / کنترل هوشمند'), ('icon-flask', 'آزمایشگاه / تحقیق'), ('icon-certificate', 'گواهی / استاندارد'), ('icon-layers', 'لایه\u200cها / ماژولار'), ('icon-target', 'هدف / دقت عملکرد'), ('icon-chart', 'نمودار / بهره\u200cوری'), ('icon-globe', 'جهانی / صادرات'), ('icon-hospital', 'درمان / بیمارستان'), ('icon-wrench', 'سرویس و نگهداری'), ('icon-clock', 'زمان / ساعات کاری'), ('icon-users', 'تیم / نیروی انسانی'), ('icon-box', 'محصول / بسته\u200cبندی'), ('icon-check', 'تأیید / کیفیت'), ('icon-spark', 'نوآوری'), ('icon-pin', 'موقعیت مکانی'), ('icon-phone', 'تلفن'), ('icon-mail', 'ایمیل')], default='icon-cog', help_text='آیکون برداری از فهرست آماده؛ نیازی به آپلود تصویر نیست.', max_length=40, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='applications/', verbose_name='تصویر (اختیاری)')),
            ],
            options={
                'verbose_name': 'حوزه کاربرد',
                'verbose_name_plural': 'حوزه\u200cهای کاربرد',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=150, null=True, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('icon', models.CharField(choices=[('icon-molecule', 'مولکول / اکسیژن'), ('icon-gauge', 'فشارسنج / دقت'), ('icon-shield', 'سپر / ایمنی'), ('icon-support', 'پشتیبانی فنی'), ('icon-cog', 'چرخ\u200cدنده / مهندسی'), ('icon-factory', 'کارخانه / تولید'), ('icon-chip', 'مدار / کنترل هوشمند'), ('icon-flask', 'آزمایشگاه / تحقیق'), ('icon-certificate', 'گواهی / استاندارد'), ('icon-layers', 'لایه\u200cها / ماژولار'), ('icon-target', 'هدف / دقت عملکرد'), ('icon-chart', 'نمودار / بهره\u200cوری'), ('icon-globe', 'جهانی / صادرات'), ('icon-hospital', 'درمان / بیمارستان'), ('icon-wrench', 'سرویس و نگهداری'), ('icon-clock', 'زمان / ساعات کاری'), ('icon-users', 'تیم / نیروی انسانی'), ('icon-box', 'محصول / بسته\u200cبندی'), ('icon-check', 'تأیید / کیفیت'), ('icon-spark', 'نوآوری'), ('icon-pin', 'موقعیت مکانی'), ('icon-phone', 'تلفن'), ('icon-mail', 'ایمیل')], default='icon-cog', help_text='آیکون برداری از فهرست آماده؛ نیازی به آپلود تصویر نیست.', max_length=40, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
            ],
            options={
                'verbose_name': 'توانمندی',
                'verbose_name_plural': 'توانمندی\u200cهای مهندسی و تولید',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=150, null=True, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('icon', models.CharField(choices=[('icon-molecule', 'مولکول / اکسیژن'), ('icon-gauge', 'فشارسنج / دقت'), ('icon-shield', 'سپر / ایمنی'), ('icon-support', 'پشتیبانی فنی'), ('icon-cog', 'چرخ\u200cدنده / مهندسی'), ('icon-factory', 'کارخانه / تولید'), ('icon-chip', 'مدار / کنترل هوشمند'), ('icon-flask', 'آزمایشگاه / تحقیق'), ('icon-certificate', 'گواهی / استاندارد'), ('icon-layers', 'لایه\u200cها / ماژولار'), ('icon-target', 'هدف / دقت عملکرد'), ('icon-chart', 'نمودار / بهره\u200cوری'), ('icon-globe', 'جهانی / صادرات'), ('icon-hospital', 'درمان / بیمارستان'), ('icon-wrench', 'سرویس و نگهداری'), ('icon-clock', 'زمان / ساعات کاری'), ('icon-users', 'تیم / نیروی انسانی'), ('icon-box', 'محصول / بسته\u200cبندی'), ('icon-check', 'تأیید / کیفیت'), ('icon-spark', 'نوآوری'), ('icon-pin', 'موقعیت مکانی'), ('icon-phone', 'تلفن'), ('icon-mail', 'ایمیل')], default='icon-cog', help_text='آیکون برداری از فهرست آماده؛ نیازی به آپلود تصویر نیست.', max_length=40, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
                ('issuer', models.CharField(blank=True, max_length=150, verbose_name='مرجع صدور')),
                ('issuer_fa', models.CharField(blank=True, max_length=150, null=True, verbose_name='مرجع صدور')),
                ('issuer_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='مرجع صدور')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications/', verbose_name='تصویر گواهی (اختیاری)')),
            ],
            options={
                'verbose_name': 'استاندارد / گواهی\u200cنامه',
                'verbose_name_plural': 'استانداردها و گواهی\u200cنامه\u200cها',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='پرسش')),
                ('question_fa', models.CharField(max_length=250, null=True, verbose_name='پرسش')),
                ('question_en', models.CharField(max_length=250, null=True, verbose_name='پرسش')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('answer_fa', models.TextField(null=True, verbose_name='پاسخ')),
                ('answer_en', models.TextField(null=True, verbose_name='پاسخ')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
            ],
            options={
                'verbose_name': 'پرسش پرتکرار',
                'verbose_name_plural': 'پرسش\u200cهای پرتکرار',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, verbose_name='سال')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=150, null=True, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
            ],
            options={
                'verbose_name': 'نقطه عطف',
                'verbose_name_plural': 'نقاط عطف (خط زمانی)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='شماره مرحله')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان مرحله')),
                ('title_fa', models.CharField(max_length=150, null=True, verbose_name='عنوان مرحله')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='عنوان مرحله')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
            ],
            options={
                'verbose_name': 'مرحله فرایند',
                'verbose_name_plural': 'فرایند همکاری',
                'ordering': ['step_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='مثال: ۱۵ یا 250 — فقط عدد را وارد کنید.', max_length=20, verbose_name='عدد')),
                ('suffix', models.CharField(blank=True, help_text='مثال: +، سال، دستگاه', max_length=20, verbose_name='پسوند')),
                ('suffix_fa', models.CharField(blank=True, help_text='مثال: +، سال، دستگاه', max_length=20, null=True, verbose_name='پسوند')),
                ('suffix_en', models.CharField(blank=True, help_text='مثال: +، سال، دستگاه', max_length=20, null=True, verbose_name='پسوند')),
                ('label', models.CharField(max_length=120, verbose_name='عنوان')),
                ('label_fa', models.CharField(max_length=120, null=True, verbose_name='عنوان')),
                ('label_en', models.CharField(max_length=120, null=True, verbose_name='عنوان')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
            ],
            options={
                'verbose_name': 'آمار / دستاورد',
                'verbose_name_plural': 'آمار و دستاوردها',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='متن نظر')),
                ('quote_fa', models.TextField(null=True, verbose_name='متن نظر')),
                ('quote_en', models.TextField(null=True, verbose_name='متن نظر')),
                ('author', models.CharField(max_length=150, verbose_name='نام گوینده')),
                ('author_fa', models.CharField(max_length=150, null=True, verbose_name='نام گوینده')),
                ('author_en', models.CharField(max_length=150, null=True, verbose_name='نام گوینده')),
                ('role', models.CharField(blank=True, max_length=150, verbose_name='سمت / سازمان')),
                ('role_fa', models.CharField(blank=True, max_length=150, null=True, verbose_name='سمت / سازمان')),
                ('role_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='سمت / سازمان')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
            ],
            options={
                'verbose_name': 'نظر مشتری',
                'verbose_name_plural': 'نظرات مشتریان',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'id'], 'verbose_name': 'خدمت', 'verbose_name_plural': 'خدمات'},
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='تصویر صفحه درباره ما'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='cta_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='متن بخش فراخوان'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='cta_text_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='متن بخش فراخوان'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='cta_text_fa',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='متن بخش فراخوان'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='cta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان بخش فراخوان'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='cta_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان بخش فراخوان'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='cta_title_fa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان بخش فراخوان'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='fax',
            field=models.CharField(blank=True, max_length=20, verbose_name='فکس'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='تصویر افقی و باکیفیت از محصول یا خط تولید. در صورت خالی بودن، لوگو نمایش داده می\u200cشود.', null=True, upload_to='company/', verbose_name='تصویر صفحه اول'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_title',
            field=models.CharField(blank=True, help_text='اگر خالی بماند، نام شرکت نمایش داده می\u200cشود.', max_length=200, verbose_name='تیتر اصلی صفحه اول'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_title_en',
            field=models.CharField(blank=True, help_text='اگر خالی بماند، نام شرکت نمایش داده می\u200cشود.', max_length=200, null=True, verbose_name='تیتر اصلی صفحه اول'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_title_fa',
            field=models.CharField(blank=True, help_text='اگر خالی بماند، نام شرکت نمایش داده می\u200cشود.', max_length=200, null=True, verbose_name='تیتر اصلی صفحه اول'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='intro_text',
            field=models.TextField(blank=True, verbose_name='متن بخش معرفی شرکت'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='intro_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='متن بخش معرفی شرکت'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='intro_text_fa',
            field=models.TextField(blank=True, null=True, verbose_name='متن بخش معرفی شرکت'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='intro_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان بخش معرفی شرکت'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='intro_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان بخش معرفی شرکت'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='intro_title_fa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان بخش معرفی شرکت'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='آدرس iframe نقشه گوگل یا نشان. در صفحه تماس نمایش داده می\u200cشود.', verbose_name='لینک نقشه (embed)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='meta_description',
            field=models.CharField(blank=True, help_text='حدود ۱۵۰ کاراکتر؛ در نتایج گوگل نمایش داده می\u200cشود.', max_length=300, verbose_name='توضیح متا (پیش\u200cفرض سایت)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='meta_description_en',
            field=models.CharField(blank=True, help_text='حدود ۱۵۰ کاراکتر؛ در نتایج گوگل نمایش داده می\u200cشود.', max_length=300, null=True, verbose_name='توضیح متا (پیش\u200cفرض سایت)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='meta_description_fa',
            field=models.CharField(blank=True, help_text='حدود ۱۵۰ کاراکتر؛ در نتایج گوگل نمایش داده می\u200cشود.', max_length=300, null=True, verbose_name='توضیح متا (پیش\u200cفرض سایت)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='mission_text',
            field=models.TextField(blank=True, verbose_name='مأموریت شرکت'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='mission_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='مأموریت شرکت'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='mission_text_fa',
            field=models.TextField(blank=True, null=True, verbose_name='مأموریت شرکت'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='اگر خالی بماند، پیام\u200cها فقط در پنل مدیریت ذخیره می\u200cشوند.', max_length=254, verbose_name='ایمیل دریافت پیام\u200cهای فرم تماس'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='og_image',
            field=models.ImageField(blank=True, help_text='تصویری که هنگام اشتراک لینک سایت در شبکه\u200cهای اجتماعی نمایش داده می\u200cشود.', null=True, upload_to='company/', verbose_name='تصویر اشتراک\u200cگذاری'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='sales_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل فروش'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='تلفن دوم'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='vision_text',
            field=models.TextField(blank=True, verbose_name='چشم\u200cانداز شرکت'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='vision_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='چشم\u200cانداز شرکت'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='vision_text_fa',
            field=models.TextField(blank=True, null=True, verbose_name='چشم\u200cانداز شرکت'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='whatsapp_url',
            field=models.URLField(blank=True, verbose_name='لینک واتس\u200cاپ'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='لینک یوتیوب'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='در صورت آپلود، جایگزین آیکون می\u200cشود.', null=True, upload_to='services/', verbose_name='تصویر (اختیاری)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('icon-molecule', 'مولکول / اکسیژن'), ('icon-gauge', 'فشارسنج / دقت'), ('icon-shield', 'سپر / ایمنی'), ('icon-support', 'پشتیبانی فنی'), ('icon-cog', 'چرخ\u200cدنده / مهندسی'), ('icon-factory', 'کارخانه / تولید'), ('icon-chip', 'مدار / کنترل هوشمند'), ('icon-flask', 'آزمایشگاه / تحقیق'), ('icon-certificate', 'گواهی / استاندارد'), ('icon-layers', 'لایه\u200cها / ماژولار'), ('icon-target', 'هدف / دقت عملکرد'), ('icon-chart', 'نمودار / بهره\u200cوری'), ('icon-globe', 'جهانی / صادرات'), ('icon-hospital', 'درمان / بیمارستان'), ('icon-wrench', 'سرویس و نگهداری'), ('icon-clock', 'زمان / ساعات کاری'), ('icon-users', 'تیم / نیروی انسانی'), ('icon-box', 'محصول / بسته\u200cبندی'), ('icon-check', 'تأیید / کیفیت'), ('icon-spark', 'نوآوری'), ('icon-pin', 'موقعیت مکانی'), ('icon-phone', 'تلفن'), ('icon-mail', 'ایمیل')], default='icon-cog', help_text='آیکون برداری از فهرست آماده؛ نیازی به آپلود تصویر نیست.', max_length=40, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=150, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_fa',
            field=models.CharField(max_length=150, null=True, verbose_name='عنوان'),
        ),
    ]
