# Generated by Django 6.1 on 2026-09-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_advantage_application_capability_certification_faq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='global_text',
            field=models.TextField(blank=True, help_text='موقعیت شرکت برای صادرات و همکاری بین\u200cالمللی. از ادعاهای تأییدنشده پرهیز کنید.', verbose_name='متن بخش بازار جهانی'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='global_text_en',
            field=models.TextField(blank=True, help_text='موقعیت شرکت برای صادرات و همکاری بین\u200cالمللی. از ادعاهای تأییدنشده پرهیز کنید.', null=True, verbose_name='متن بخش بازار جهانی'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='global_text_fa',
            field=models.TextField(blank=True, help_text='موقعیت شرکت برای صادرات و همکاری بین\u200cالمللی. از ادعاهای تأییدنشده پرهیز کنید.', null=True, verbose_name='متن بخش بازار جهانی'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='global_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان بخش بازار جهانی'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='global_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان بخش بازار جهانی'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='global_title_fa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان بخش بازار جهانی'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='icon',
            field=models.CharField(choices=[('icon-oxygen', 'اکسیژن (مولکول)'), ('icon-mask', 'ماسک تنفسی'), ('icon-cylinder', 'سیلندر / دستگاه قابل حمل'), ('icon-gauge', 'فشارسنج / دقت اندازه\u200cگیری'), ('icon-aircraft', 'هواپیما'), ('icon-cabin', 'کابین هواپیما'), ('icon-altitude', 'ارتفاع پرواز'), ('icon-shield', 'ایمنی'), ('icon-certificate', 'استاندارد / گواهی'), ('icon-cog', 'مهندسی طراحی'), ('icon-wrench', 'سرویس و نگهداری'), ('icon-factory', 'تولید و مونتاژ'), ('icon-chip', 'الکترونیک و کنترل'), ('icon-flask', 'آزمون و آزمایشگاه'), ('icon-layers', 'طراحی ماژولار'), ('icon-target', 'دقت عملکرد'), ('icon-chart', 'عملکرد و بهره\u200cوری'), ('icon-clipboard', 'مستندسازی و کنترل کیفیت'), ('icon-weight', 'وزن سبک'), ('icon-thermometer', 'شرایط محیطی'), ('icon-globe', 'بازار جهانی / صادرات'), ('icon-route', 'زنجیره تأمین و تحویل'), ('icon-handshake', 'همکاری و نمایندگی'), ('icon-headset', 'پشتیبانی فنی'), ('icon-hospital', 'کاربرد درمانی'), ('icon-users', 'تیم و نیروی انسانی'), ('icon-box', 'محصول / بسته\u200cبندی'), ('icon-check-circle', 'تأیید / انطباق'), ('icon-spark', 'نوآوری'), ('icon-pin', 'موقعیت مکانی'), ('icon-phone', 'تلفن'), ('icon-mail', 'ایمیل'), ('icon-clock', 'ساعات کاری')], default='icon-cog', help_text='آیکون برداری از فهرست آماده؛ نیازی به آپلود تصویر نیست.', max_length=40, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='application',
            name='icon',
            field=models.CharField(choices=[('icon-oxygen', 'اکسیژن (مولکول)'), ('icon-mask', 'ماسک تنفسی'), ('icon-cylinder', 'سیلندر / دستگاه قابل حمل'), ('icon-gauge', 'فشارسنج / دقت اندازه\u200cگیری'), ('icon-aircraft', 'هواپیما'), ('icon-cabin', 'کابین هواپیما'), ('icon-altitude', 'ارتفاع پرواز'), ('icon-shield', 'ایمنی'), ('icon-certificate', 'استاندارد / گواهی'), ('icon-cog', 'مهندسی طراحی'), ('icon-wrench', 'سرویس و نگهداری'), ('icon-factory', 'تولید و مونتاژ'), ('icon-chip', 'الکترونیک و کنترل'), ('icon-flask', 'آزمون و آزمایشگاه'), ('icon-layers', 'طراحی ماژولار'), ('icon-target', 'دقت عملکرد'), ('icon-chart', 'عملکرد و بهره\u200cوری'), ('icon-clipboard', 'مستندسازی و کنترل کیفیت'), ('icon-weight', 'وزن سبک'), ('icon-thermometer', 'شرایط محیطی'), ('icon-globe', 'بازار جهانی / صادرات'), ('icon-route', 'زنجیره تأمین و تحویل'), ('icon-handshake', 'همکاری و نمایندگی'), ('icon-headset', 'پشتیبانی فنی'), ('icon-hospital', 'کاربرد درمانی'), ('icon-users', 'تیم و نیروی انسانی'), ('icon-box', 'محصول / بسته\u200cبندی'), ('icon-check-circle', 'تأیید / انطباق'), ('icon-spark', 'نوآوری'), ('icon-pin', 'موقعیت مکانی'), ('icon-phone', 'تلفن'), ('icon-mail', 'ایمیل'), ('icon-clock', 'ساعات کاری')], default='icon-cog', help_text='آیکون برداری از فهرست آماده؛ نیازی به آپلود تصویر نیست.', max_length=40, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='capability',
            name='icon',
            field=models.CharField(choices=[('icon-oxygen', 'اکسیژن (مولکول)'), ('icon-mask', 'ماسک تنفسی'), ('icon-cylinder', 'سیلندر / دستگاه قابل حمل'), ('icon-gauge', 'فشارسنج / دقت اندازه\u200cگیری'), ('icon-aircraft', 'هواپیما'), ('icon-cabin', 'کابین هواپیما'), ('icon-altitude', 'ارتفاع پرواز'), ('icon-shield', 'ایمنی'), ('icon-certificate', 'استاندارد / گواهی'), ('icon-cog', 'مهندسی طراحی'), ('icon-wrench', 'سرویس و نگهداری'), ('icon-factory', 'تولید و مونتاژ'), ('icon-chip', 'الکترونیک و کنترل'), ('icon-flask', 'آزمون و آزمایشگاه'), ('icon-layers', 'طراحی ماژولار'), ('icon-target', 'دقت عملکرد'), ('icon-chart', 'عملکرد و بهره\u200cوری'), ('icon-clipboard', 'مستندسازی و کنترل کیفیت'), ('icon-weight', 'وزن سبک'), ('icon-thermometer', 'شرایط محیطی'), ('icon-globe', 'بازار جهانی / صادرات'), ('icon-route', 'زنجیره تأمین و تحویل'), ('icon-handshake', 'همکاری و نمایندگی'), ('icon-headset', 'پشتیبانی فنی'), ('icon-hospital', 'کاربرد درمانی'), ('icon-users', 'تیم و نیروی انسانی'), ('icon-box', 'محصول / بسته\u200cبندی'), ('icon-check-circle', 'تأیید / انطباق'), ('icon-spark', 'نوآوری'), ('icon-pin', 'موقعیت مکانی'), ('icon-phone', 'تلفن'), ('icon-mail', 'ایمیل'), ('icon-clock', 'ساعات کاری')], default='icon-cog', help_text='آیکون برداری از فهرست آماده؛ نیازی به آپلود تصویر نیست.', max_length=40, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='icon',
            field=models.CharField(choices=[('icon-oxygen', 'اکسیژن (مولکول)'), ('icon-mask', 'ماسک تنفسی'), ('icon-cylinder', 'سیلندر / دستگاه قابل حمل'), ('icon-gauge', 'فشارسنج / دقت اندازه\u200cگیری'), ('icon-aircraft', 'هواپیما'), ('icon-cabin', 'کابین هواپیما'), ('icon-altitude', 'ارتفاع پرواز'), ('icon-shield', 'ایمنی'), ('icon-certificate', 'استاندارد / گواهی'), ('icon-cog', 'مهندسی طراحی'), ('icon-wrench', 'سرویس و نگهداری'), ('icon-factory', 'تولید و مونتاژ'), ('icon-chip', 'الکترونیک و کنترل'), ('icon-flask', 'آزمون و آزمایشگاه'), ('icon-layers', 'طراحی ماژولار'), ('icon-target', 'دقت عملکرد'), ('icon-chart', 'عملکرد و بهره\u200cوری'), ('icon-clipboard', 'مستندسازی و کنترل کیفیت'), ('icon-weight', 'وزن سبک'), ('icon-thermometer', 'شرایط محیطی'), ('icon-globe', 'بازار جهانی / صادرات'), ('icon-route', 'زنجیره تأمین و تحویل'), ('icon-handshake', 'همکاری و نمایندگی'), ('icon-headset', 'پشتیبانی فنی'), ('icon-hospital', 'کاربرد درمانی'), ('icon-users', 'تیم و نیروی انسانی'), ('icon-box', 'محصول / بسته\u200cبندی'), ('icon-check-circle', 'تأیید / انطباق'), ('icon-spark', 'نوآوری'), ('icon-pin', 'موقعیت مکانی'), ('icon-phone', 'تلفن'), ('icon-mail', 'ایمیل'), ('icon-clock', 'ساعات کاری')], default='icon-cog', help_text='آیکون برداری از فهرست آماده؛ نیازی به آپلود تصویر نیست.', max_length=40, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('icon-oxygen', 'اکسیژن (مولکول)'), ('icon-mask', 'ماسک تنفسی'), ('icon-cylinder', 'سیلندر / دستگاه قابل حمل'), ('icon-gauge', 'فشارسنج / دقت اندازه\u200cگیری'), ('icon-aircraft', 'هواپیما'), ('icon-cabin', 'کابین هواپیما'), ('icon-altitude', 'ارتفاع پرواز'), ('icon-shield', 'ایمنی'), ('icon-certificate', 'استاندارد / گواهی'), ('icon-cog', 'مهندسی طراحی'), ('icon-wrench', 'سرویس و نگهداری'), ('icon-factory', 'تولید و مونتاژ'), ('icon-chip', 'الکترونیک و کنترل'), ('icon-flask', 'آزمون و آزمایشگاه'), ('icon-layers', 'طراحی ماژولار'), ('icon-target', 'دقت عملکرد'), ('icon-chart', 'عملکرد و بهره\u200cوری'), ('icon-clipboard', 'مستندسازی و کنترل کیفیت'), ('icon-weight', 'وزن سبک'), ('icon-thermometer', 'شرایط محیطی'), ('icon-globe', 'بازار جهانی / صادرات'), ('icon-route', 'زنجیره تأمین و تحویل'), ('icon-handshake', 'همکاری و نمایندگی'), ('icon-headset', 'پشتیبانی فنی'), ('icon-hospital', 'کاربرد درمانی'), ('icon-users', 'تیم و نیروی انسانی'), ('icon-box', 'محصول / بسته\u200cبندی'), ('icon-check-circle', 'تأیید / انطباق'), ('icon-spark', 'نوآوری'), ('icon-pin', 'موقعیت مکانی'), ('icon-phone', 'تلفن'), ('icon-mail', 'ایمیل'), ('icon-clock', 'ساعات کاری')], default='icon-cog', help_text='آیکون برداری از فهرست آماده؛ نیازی به آپلود تصویر نیست.', max_length=40, verbose_name='آیکون'),
        ),
    ]
