# Generated by Django 6.1 on 2026-09-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_companyinfo_global_text_companyinfo_global_text_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, help_text='اگر خالی بماند، نشان برداری داخلی اطلس در هدر و فوتر استفاده می\u200cشود.', null=True, upload_to='company/', verbose_name='لوگو'),
        ),
    ]
