# Generated by Django 6.1 on 2026-09-04 15:16

import core.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_companyinfo_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=150, null=True, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('icon', models.CharField(choices=[('icon-oxygen', 'اکسیژن (مولکول)'), ('icon-mask', 'ماسک تنفسی'), ('icon-cylinder', 'سیلندر / دستگاه قابل حمل'), ('icon-gauge', 'فشارسنج / دقت اندازه\u200cگیری'), ('icon-aircraft', 'هواپیما'), ('icon-cabin', 'کابین هواپیما'), ('icon-altitude', 'ارتفاع پرواز'), ('icon-shield', 'ایمنی'), ('icon-certificate', 'استاندارد / گواهی'), ('icon-cog', 'مهندسی طراحی'), ('icon-wrench', 'سرویس و نگهداری'), ('icon-factory', 'تولید و مونتاژ'), ('icon-chip', 'الکترونیک و کنترل'), ('icon-flask', 'آزمون و آزمایشگاه'), ('icon-layers', 'طراحی ماژولار'), ('icon-target', 'دقت عملکرد'), ('icon-chart', 'عملکرد و بهره\u200cوری'), ('icon-clipboard', 'مستندسازی و کنترل کیفیت'), ('icon-weight', 'وزن سبک'), ('icon-thermometer', 'شرایط محیطی'), ('icon-globe', 'بازار جهانی / صادرات'), ('icon-route', 'زنجیره تأمین و تحویل'), ('icon-handshake', 'همکاری و نمایندگی'), ('icon-headset', 'پشتیبانی فنی'), ('icon-hospital', 'کاربرد درمانی'), ('icon-users', 'تیم و نیروی انسانی'), ('icon-box', 'محصول / بسته\u200cبندی'), ('icon-check-circle', 'تأیید / انطباق'), ('icon-spark', 'نوآوری'), ('icon-pin', 'موقعیت مکانی'), ('icon-phone', 'تلفن'), ('icon-mail', 'ایمیل'), ('icon-clock', 'ساعات کاری')], default='icon-cog', help_text='آیکون برداری از فهرست آماده؛ نیازی به آپلود تصویر نیست.', max_length=40, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='اگر خالی بماند، از عنوان ساخته می\u200cشود.', max_length=120, unique=True, verbose_name='نامک (URL)')),
                ('body', models.TextField(blank=True, help_text='اگر پر شود، صفحه\u200cی اختصاصی این مورد در سایت ساخته می\u200cشود.', verbose_name='متن کامل صفحه')),
                ('body_fa', models.TextField(blank=True, help_text='اگر پر شود، صفحه\u200cی اختصاصی این مورد در سایت ساخته می\u200cشود.', null=True, verbose_name='متن کامل صفحه')),
                ('body_en', models.TextField(blank=True, help_text='اگر پر شود، صفحه\u200cی اختصاصی این مورد در سایت ساخته می\u200cشود.', null=True, verbose_name='متن کامل صفحه')),
                ('meta_description', models.CharField(blank=True, help_text='اگر خالی بماند، از توضیح کوتاه استفاده می\u200cشود.', max_length=300, verbose_name='توضیح متا')),
                ('meta_description_fa', models.CharField(blank=True, help_text='اگر خالی بماند، از توضیح کوتاه استفاده می\u200cشود.', max_length=300, null=True, verbose_name='توضیح متا')),
                ('meta_description_en', models.CharField(blank=True, help_text='اگر خالی بماند، از توضیح کوتاه استفاده می\u200cشود.', max_length=300, null=True, verbose_name='توضیح متا')),
                ('image', models.ImageField(blank=True, null=True, upload_to='industries/', verbose_name='تصویر (اختیاری)')),
            ],
            options={
                'verbose_name': 'صنعت / حوزه کاربرد',
                'verbose_name_plural': 'صنعت\u200cها و حوزه\u200cهای کاربرد',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
            bases=(models.Model, core.images.OptimizedImagesMixin),
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=150, null=True, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('icon', models.CharField(choices=[('icon-oxygen', 'اکسیژن (مولکول)'), ('icon-mask', 'ماسک تنفسی'), ('icon-cylinder', 'سیلندر / دستگاه قابل حمل'), ('icon-gauge', 'فشارسنج / دقت اندازه\u200cگیری'), ('icon-aircraft', 'هواپیما'), ('icon-cabin', 'کابین هواپیما'), ('icon-altitude', 'ارتفاع پرواز'), ('icon-shield', 'ایمنی'), ('icon-certificate', 'استاندارد / گواهی'), ('icon-cog', 'مهندسی طراحی'), ('icon-wrench', 'سرویس و نگهداری'), ('icon-factory', 'تولید و مونتاژ'), ('icon-chip', 'الکترونیک و کنترل'), ('icon-flask', 'آزمون و آزمایشگاه'), ('icon-layers', 'طراحی ماژولار'), ('icon-target', 'دقت عملکرد'), ('icon-chart', 'عملکرد و بهره\u200cوری'), ('icon-clipboard', 'مستندسازی و کنترل کیفیت'), ('icon-weight', 'وزن سبک'), ('icon-thermometer', 'شرایط محیطی'), ('icon-globe', 'بازار جهانی / صادرات'), ('icon-route', 'زنجیره تأمین و تحویل'), ('icon-handshake', 'همکاری و نمایندگی'), ('icon-headset', 'پشتیبانی فنی'), ('icon-hospital', 'کاربرد درمانی'), ('icon-users', 'تیم و نیروی انسانی'), ('icon-box', 'محصول / بسته\u200cبندی'), ('icon-check-circle', 'تأیید / انطباق'), ('icon-spark', 'نوآوری'), ('icon-pin', 'موقعیت مکانی'), ('icon-phone', 'تلفن'), ('icon-mail', 'ایمیل'), ('icon-clock', 'ساعات کاری')], default='icon-cog', help_text='آیکون برداری از فهرست آماده؛ نیازی به آپلود تصویر نیست.', max_length=40, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='اگر خالی بماند، از عنوان ساخته می\u200cشود.', max_length=120, unique=True, verbose_name='نامک (URL)')),
                ('body', models.TextField(blank=True, help_text='اگر پر شود، صفحه\u200cی اختصاصی این مورد در سایت ساخته می\u200cشود.', verbose_name='متن کامل صفحه')),
                ('body_fa', models.TextField(blank=True, help_text='اگر پر شود، صفحه\u200cی اختصاصی این مورد در سایت ساخته می\u200cشود.', null=True, verbose_name='متن کامل صفحه')),
                ('body_en', models.TextField(blank=True, help_text='اگر پر شود، صفحه\u200cی اختصاصی این مورد در سایت ساخته می\u200cشود.', null=True, verbose_name='متن کامل صفحه')),
                ('meta_description', models.CharField(blank=True, help_text='اگر خالی بماند، از توضیح کوتاه استفاده می\u200cشود.', max_length=300, verbose_name='توضیح متا')),
                ('meta_description_fa', models.CharField(blank=True, help_text='اگر خالی بماند، از توضیح کوتاه استفاده می\u200cشود.', max_length=300, null=True, verbose_name='توضیح متا')),
                ('meta_description_en', models.CharField(blank=True, help_text='اگر خالی بماند، از توضیح کوتاه استفاده می\u200cشود.', max_length=300, null=True, verbose_name='توضیح متا')),
                ('image', models.ImageField(blank=True, help_text='در کارت و بالای صفحه\u200cی این فناوری استفاده می\u200cشود.', null=True, upload_to='technologies/', verbose_name='تصویر (اختیاری)')),
            ],
            options={
                'verbose_name': 'حوزه فناوری',
                'verbose_name_plural': 'حوزه\u200cهای فناوری',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
            bases=(models.Model, core.images.OptimizedImagesMixin),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.AlterModelOptions(
            name='advantage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'تمایز', 'verbose_name_plural': 'تمایزها (چرا اطلس)'},
        ),
    ]
