# Generated by Django 6.1 on 2026-09-30 15:40

import core.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_atlas_company_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام مشتری')),
                ('name_fa', models.CharField(max_length=150, null=True, verbose_name='نام مشتری')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='نام مشتری')),
                ('logo', models.ImageField(upload_to='clients/', verbose_name='لوگو')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ['order', 'id'],
            },
            bases=(core.images.OptimizedImagesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='نام شرکت یا سازمان صادرکننده\u200cی نامه.', max_length=150, verbose_name='صادرکننده')),
                ('title_fa', models.CharField(help_text='نام شرکت یا سازمان صادرکننده\u200cی نامه.', max_length=150, null=True, verbose_name='صادرکننده')),
                ('title_en', models.CharField(help_text='نام شرکت یا سازمان صادرکننده\u200cی نامه.', max_length=150, null=True, verbose_name='صادرکننده')),
                ('image', models.ImageField(upload_to='endorsements/', verbose_name='تصویر نامه')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
            ],
            options={
                'verbose_name': 'رضایت\u200cنامه',
                'verbose_name_plural': 'رضایت\u200cنامه\u200cها',
                'ordering': ['order', 'id'],
            },
            bases=(core.images.OptimizedImagesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='توضیح تصویر')),
                ('caption_fa', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیح تصویر')),
                ('caption_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیح تصویر')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'گالری تصاویر شرکت',
                'ordering': ['order', 'id'],
            },
            bases=(core.images.OptimizedImagesMixin, models.Model),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='intro_image',
            field=models.ImageField(blank=True, help_text='اگر خالی بماند، تصویر صفحه\u200cی درباره ما نمایش داده می\u200cشود.', null=True, upload_to='company/', verbose_name='تصویر بخش معرفی (هدف بنیادین)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='mission_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='تصویر مأموریت'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='products_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='تصویر سربرگ صفحه\u200cی محصولات'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='slogan',
            field=models.CharField(blank=True, help_text='جمله\u200cی کوتاهی که در نوار تصویری صفحه\u200cی اصلی نمایش داده می\u200cشود.', max_length=300, verbose_name='شعار برند'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='slogan_en',
            field=models.CharField(blank=True, help_text='جمله\u200cی کوتاهی که در نوار تصویری صفحه\u200cی اصلی نمایش داده می\u200cشود.', max_length=300, null=True, verbose_name='شعار برند'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='slogan_fa',
            field=models.CharField(blank=True, help_text='جمله\u200cی کوتاهی که در نوار تصویری صفحه\u200cی اصلی نمایش داده می\u200cشود.', max_length=300, null=True, verbose_name='شعار برند'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='slogan_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='تصویر پس\u200cزمینه\u200cی شعار برند'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='trust_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='تصویر پس\u200cزمینه\u200cی نوار اعتماد (آمار)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='values_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='تصویر بخش ارزش\u200cهای بنیادین'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='vision_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='تصویر چشم\u200cانداز'),
        ),
    ]
