# Generated by Django 6.1 on 2026-09-30 15:41

import core.images
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_client_endorsement_galleryimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/', verbose_name='تصویر')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'تصویر خدمت',
                'verbose_name_plural': 'تصاویر تکمیلی خدمت',
                'ordering': ['order', 'id'],
            },
            bases=(core.images.OptimizedImagesMixin, models.Model),
        ),
    ]
