# Generated by Django 6.1 on 2026-10-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_serviceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='economic_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='شماره اقتصادی'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='national_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='شناسه ملی'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='registration_date',
            field=models.CharField(blank=True, help_text='به همان شکلی که باید نمایش داده شود، مثلاً ۱۳۹۸/۰۴/۰۲.', max_length=20, verbose_name='تاریخ ثبت'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='registration_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='شماره ثبت'),
        ),
    ]
