# Generated by Django 6.1 on 2026-08-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_en',
            field=models.CharField(max_length=150, null=True, verbose_name='سمت'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_fa',
            field=models.CharField(max_length=150, null=True, verbose_name='سمت'),
        ),
    ]
