# Generated by Django 6.1 on 2026-09-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_teammember_bio_en_teammember_bio_fa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'id'], 'verbose_name': 'عضو تیم', 'verbose_name_plural': 'اعضای تیم'},
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل کاری'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_name_fa',
            field=models.CharField(max_length=150, null=True, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='لینک لینکدین'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
