# Generated by Django 6.1 on 2026-09-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_teammember_options_teammember_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, help_text='اگر خالی بماند، حروف اول نام در یک قاب ساده نمایش داده می\u200cشود.', null=True, upload_to='team/', verbose_name='عکس پرسنلی'),
        ),
    ]
