# Generated by Django 6.1 on 2026-09-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_teammember_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(blank=True, max_length=150, verbose_name='سمت'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='سمت'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position_fa',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='سمت'),
        ),
    ]
