# Generated by Django 6.1 on 2026-09-04 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('products', '0003_productapplication_productdocument_productfeature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='یادداشت داخلی'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='company',
            field=models.CharField(blank=True, max_length=150, verbose_name='نام سازمان'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='related_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='products.product', verbose_name='محصول مرتبط'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('in_progress', 'در حال بررسی'), ('answered', 'پاسخ داده شده'), ('archived', 'بایگانی')], db_index=True, default='new', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='topic',
            field=models.CharField(choices=[('sales', 'استعلام قیمت و خرید'), ('technical', 'پرسش فنی'), ('support', 'پشتیبانی و خدمات پس از فروش'), ('partnership', 'همکاری و نمایندگی'), ('other', 'سایر موارد')], default='sales', max_length=20, verbose_name='موضوع درخواست'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['is_read', '-created_at'], name='contact_unread_idx'),
        ),
    ]
