# Generated by Django 6.1 on 2026-08-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='نام دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='نام دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='توضیحات کامل'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fa',
            field=models.TextField(null=True, verbose_name='توضیحات کامل'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(max_length=300, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_fa',
            field=models.CharField(max_length=300, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications_en',
            field=models.TextField(blank=True, null=True, verbose_name='مشخصات فنی'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications_fa',
            field=models.TextField(blank=True, null=True, verbose_name='مشخصات فنی'),
        ),
    ]
