# Generated by Django 6.1 on 2026-09-04 11:47

import core.images
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_name_en_category_name_fa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان کاربرد')),
                ('title_fa', models.CharField(max_length=150, null=True, verbose_name='عنوان کاربرد')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='عنوان کاربرد')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'کاربرد محصول',
                'verbose_name_plural': 'کاربردهای محصول',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان مدرک')),
                ('title_fa', models.CharField(max_length=150, null=True, verbose_name='عنوان مدرک')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='عنوان مدرک')),
                ('file', models.FileField(upload_to='products/documents/', verbose_name='فایل')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'مدرک فنی',
                'verbose_name_plural': 'مدارک و کاتالوگ\u200cها',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان ویژگی')),
                ('title_fa', models.CharField(max_length=150, null=True, verbose_name='عنوان ویژگی')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='عنوان ویژگی')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی\u200cهای محصول',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, help_text='برای دسترس\u200cپذیری و سئو مفید است (متن alt).', max_length=200, verbose_name='توضیح تصویر')),
                ('caption_fa', models.CharField(blank=True, help_text='برای دسترس\u200cپذیری و سئو مفید است (متن alt).', max_length=200, null=True, verbose_name='توضیح تصویر')),
                ('caption_en', models.CharField(blank=True, help_text='برای دسترس\u200cپذیری و سئو مفید است (متن alt).', max_length=200, null=True, verbose_name='توضیح تصویر')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'گالری تصاویر',
                'ordering': ['order', 'id'],
            },
            bases=(core.images.OptimizedImagesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, help_text='مثال: عملکرد، ابعاد، برق. ردیف\u200cهای هم\u200cگروه کنار هم نمایش داده می\u200cشوند.', max_length=100, verbose_name='گروه')),
                ('group_fa', models.CharField(blank=True, help_text='مثال: عملکرد، ابعاد، برق. ردیف\u200cهای هم\u200cگروه کنار هم نمایش داده می\u200cشوند.', max_length=100, null=True, verbose_name='گروه')),
                ('group_en', models.CharField(blank=True, help_text='مثال: عملکرد، ابعاد، برق. ردیف\u200cهای هم\u200cگروه کنار هم نمایش داده می\u200cشوند.', max_length=100, null=True, verbose_name='گروه')),
                ('label', models.CharField(max_length=150, verbose_name='عنوان مشخصه')),
                ('label_fa', models.CharField(max_length=150, null=True, verbose_name='عنوان مشخصه')),
                ('label_en', models.CharField(max_length=150, null=True, verbose_name='عنوان مشخصه')),
                ('value', models.CharField(max_length=250, verbose_name='مقدار')),
                ('value_fa', models.CharField(max_length=250, null=True, verbose_name='مقدار')),
                ('value_en', models.CharField(max_length=250, null=True, verbose_name='مقدار')),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='واحد')),
                ('unit_fa', models.CharField(blank=True, max_length=40, null=True, verbose_name='واحد')),
                ('unit_en', models.CharField(blank=True, max_length=40, null=True, verbose_name='واحد')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'مشخصه فنی',
                'verbose_name_plural': 'مشخصات فنی',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیح دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='محصولات شاخص در صفحه اصلی نمایش داده می\u200cشوند.', verbose_name='محصول شاخص'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='اگر خالی بماند، از توضیح کوتاه استفاده می\u200cشود.', max_length=300, verbose_name='توضیح متا'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_en',
            field=models.CharField(blank=True, help_text='اگر خالی بماند، از توضیح کوتاه استفاده می\u200cشود.', max_length=300, null=True, verbose_name='توضیح متا'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_fa',
            field=models.CharField(blank=True, help_text='اگر خالی بماند، از توضیح کوتاه استفاده می\u200cشود.', max_length=300, null=True, verbose_name='توضیح متا'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_code',
            field=models.CharField(blank=True, help_text='مثال: ATLAS-OG-500', max_length=60, verbose_name='کد / مدل محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='نامک (URL)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='نامک (URL)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, help_text='برای جدول مشخصات، از بخش «مشخصات فنی» پایین همین صفحه استفاده کنید. این فیلد برای توضیحات تکمیلی است.', verbose_name='مشخصات فنی (متن آزاد)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications_en',
            field=models.TextField(blank=True, help_text='برای جدول مشخصات، از بخش «مشخصات فنی» پایین همین صفحه استفاده کنید. این فیلد برای توضیحات تکمیلی است.', null=True, verbose_name='مشخصات فنی (متن آزاد)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications_fa',
            field=models.TextField(blank=True, help_text='برای جدول مشخصات، از بخش «مشخصات فنی» پایین همین صفحه استفاده کنید. این فیلد برای توضیحات تکمیلی است.', null=True, verbose_name='مشخصات فنی (متن آزاد)'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'order'], name='product_active_order_idx'),
        ),
        migrations.AddField(
            model_name='productapplication',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='products.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='productdocument',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='products.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='products.product', verbose_name='محصول'),
        ),
    ]
