# Generated by Django 6.1 on 2026-09-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productapplication_productdocument_productfeature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='is_highlight',
            field=models.BooleanField(default=False, help_text='مشخصه\u200cهای علامت\u200cخورده بالای صفحه\u200cی محصول به\u200cعنوان سنجه\u200cهای کلیدی دیده می\u200cشوند.', verbose_name='نمایش در نوار شاخص'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='group',
            field=models.CharField(blank=True, help_text='مثال: عملکرد، ابعاد، محیط کار. ردیف\u200cهای هم\u200cگروه کنار هم نمایش داده می\u200cشوند.', max_length=100, verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='group_en',
            field=models.CharField(blank=True, help_text='مثال: عملکرد، ابعاد، محیط کار. ردیف\u200cهای هم\u200cگروه کنار هم نمایش داده می\u200cشوند.', max_length=100, null=True, verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='group_fa',
            field=models.CharField(blank=True, help_text='مثال: عملکرد، ابعاد، محیط کار. ردیف\u200cهای هم\u200cگروه کنار هم نمایش داده می\u200cشوند.', max_length=100, null=True, verbose_name='گروه'),
        ),
    ]
