# Generated by Django 6.1 on 2026-09-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productspecification_is_highlight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='عکس واقعی محصول. اگر خالی بماند، ترسیم فنی داخلی سایت نمایش داده می\u200cشود.', null=True, upload_to='products/', verbose_name='تصویر محصول'),
        ),
    ]
