# Generated by Django 6.1 on 2026-09-04 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_atlas_company_first'),
        ('products', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'خط محصول', 'verbose_name_plural': 'خطوط محصول'},
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('icon-oxygen', 'اکسیژن (مولکول)'), ('icon-mask', 'ماسک تنفسی'), ('icon-cylinder', 'سیلندر / دستگاه قابل حمل'), ('icon-gauge', 'فشارسنج / دقت اندازه\u200cگیری'), ('icon-aircraft', 'هواپیما'), ('icon-cabin', 'کابین هواپیما'), ('icon-altitude', 'ارتفاع پرواز'), ('icon-shield', 'ایمنی'), ('icon-certificate', 'استاندارد / گواهی'), ('icon-cog', 'مهندسی طراحی'), ('icon-wrench', 'سرویس و نگهداری'), ('icon-factory', 'تولید و مونتاژ'), ('icon-chip', 'الکترونیک و کنترل'), ('icon-flask', 'آزمون و آزمایشگاه'), ('icon-layers', 'طراحی ماژولار'), ('icon-target', 'دقت عملکرد'), ('icon-chart', 'عملکرد و بهره\u200cوری'), ('icon-clipboard', 'مستندسازی و کنترل کیفیت'), ('icon-weight', 'وزن سبک'), ('icon-thermometer', 'شرایط محیطی'), ('icon-globe', 'بازار جهانی / صادرات'), ('icon-route', 'زنجیره تأمین و تحویل'), ('icon-handshake', 'همکاری و نمایندگی'), ('icon-headset', 'پشتیبانی فنی'), ('icon-hospital', 'کاربرد درمانی'), ('icon-users', 'تیم و نیروی انسانی'), ('icon-box', 'محصول / بسته\u200cبندی'), ('icon-check-circle', 'تأیید / انطباق'), ('icon-spark', 'نوآوری'), ('icon-pin', 'موقعیت مکانی'), ('icon-phone', 'تلفن'), ('icon-mail', 'ایمیل'), ('icon-clock', 'ساعات کاری')], default='icon-cog', max_length=40, verbose_name='آیکون'),
        ),
        migrations.AddField(
            model_name='product',
            name='industries',
            field=models.ManyToManyField(blank=True, help_text='صنعت\u200cهایی که این محصول در آن\u200cها کاربرد دارد.', related_name='products', to='core.industry', verbose_name='صنعت\u200cها'),
        ),
        migrations.AddField(
            model_name='product',
            name='tagline',
            field=models.CharField(blank=True, help_text='یک سطر کوتاه که جایگاه محصول را مشخص می\u200cکند.', max_length=160, verbose_name='عنوان فرعی'),
        ),
        migrations.AddField(
            model_name='product',
            name='tagline_en',
            field=models.CharField(blank=True, help_text='یک سطر کوتاه که جایگاه محصول را مشخص می\u200cکند.', max_length=160, null=True, verbose_name='عنوان فرعی'),
        ),
        migrations.AddField(
            model_name='product',
            name='tagline_fa',
            field=models.CharField(blank=True, help_text='یک سطر کوتاه که جایگاه محصول را مشخص می\u200cکند.', max_length=160, null=True, verbose_name='عنوان فرعی'),
        ),
        migrations.AddField(
            model_name='product',
            name='technologies',
            field=models.ManyToManyField(blank=True, help_text='فناوری\u200cهایی که این محصول بر آن\u200cها تکیه دارد.', related_name='products', to='core.technology', verbose_name='حوزه\u200cهای فناوری'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیح خط محصول'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح خط محصول'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح خط محصول'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام خط محصول'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='نام خط محصول'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='نام خط محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='خط محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='اگر خالی بماند، یک قاب طرح\u200cدار با کد/نام محصول نمایش داده می\u200cشود.', null=True, upload_to='products/', verbose_name='تصویر محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_code',
            field=models.CharField(blank=True, max_length=60, verbose_name='کد / مدل محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, help_text='برای جدول مشخصات، از بخش «مشخصات فنی» پایین همین صفحه استفاده کنید. این فیلد برای توضیحات تکمیلی است.', verbose_name='یادداشت فنی (متن آزاد)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications_en',
            field=models.TextField(blank=True, help_text='برای جدول مشخصات، از بخش «مشخصات فنی» پایین همین صفحه استفاده کنید. این فیلد برای توضیحات تکمیلی است.', null=True, verbose_name='یادداشت فنی (متن آزاد)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications_fa',
            field=models.TextField(blank=True, help_text='برای جدول مشخصات، از بخش «مشخصات فنی» پایین همین صفحه استفاده کنید. این فیلد برای توضیحات تکمیلی است.', null=True, verbose_name='یادداشت فنی (متن آزاد)'),
        ),
    ]
