# Generated by Django 6.1 on 2026-09-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_atlas_company_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات کامل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کامل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کامل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_fa',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='اگر خالی بماند، از نام محصول ساخته می\u200cشود.', max_length=200, unique=True, verbose_name='نامک (URL)'),
        ),
    ]
